src/Entity/RendezVous.php
<?php

namespace App\Entity;

use App\Repository\RendezVousRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RendezVousRepository::class)]
class RendezVous
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $patient = null;

    #[ORM\Column(length: 255)]
    private ?string $Adresse = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure = null;

    #[ORM\Column(length: 1024)]
    private ?string $raison = null;

    #[ORM\Column]
    private ?bool $urgence = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $specificites = null;

    #[ORM\Column(length: 255)]
    private ?string $praticien_id = null;

    public function getId(): ?int
    {
        return $this->patient;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): static
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getHeure(): ?\DateTimeInterface
    {
        return $this->heure;
    }

    public function setHeure(\DateTimeInterface $heure): static
    {
        $this->heure = $heure;

        return $this;
    }

    public function getRaison(): ?string
    {
        return $this->raison;
    }

    public function setRaison(string $raison): static
    {
        $this->raison = $raison;

        return $this;
    }

    public function isUrgence(): ?bool
    {
        return $this->urgence;
    }

    public function setUrgence(bool $urgence): static
    {
        $this->urgence = $urgence;

        return $this;
    }

    public function getSpecificites(): ?string
    {
        return $this->specificites;
    }

    public function setSpecificites(?string $specificites): static
    {
        $this->specificites = $specificites;

        return $this;
    }

    public function getPraticien_id(): ?string
    {
        return $this->praticien;
    }

    public function setPraticien_id(string $praticien): static
    {
        $this->praticien = $praticien;

        return $this;
    }
}

src/Controller/PraticienControllerCrudController.php
<?php

namespace App\Controller;

use App\Entity\Praticien;
use App\Form\PraticienType;
use App\Repository\PraticienRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/praticien/controller/crud')]
class PraticienControllerCrudController extends AbstractController
{
    #[Route('/', name: 'app_praticien_controller_crud_index', methods: ['GET'])]
    public function index(PraticienRepository $praticienRepository): Response
    {
        return $this->render('praticien_controller_crud/index.html.twig', [
            'praticiens' => $praticienRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_praticien_controller_crud_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $praticien = new Praticien();
        $form = $this->createForm(PraticienType::class, $praticien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($praticien);
            $entityManager->flush();

            return $this->redirectToRoute('app_praticien_controller_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('praticien_controller_crud/new.html.twig', [
            'praticien' => $praticien,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_praticien_controller_crud_show', methods: ['GET'])]
    public function show(Praticien $praticien): Response
    {
        return $this->render('praticien_controller_crud/show.html.twig', [
            'praticien' => $praticien,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_praticien_controller_crud_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Praticien $praticien, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PraticienType::class, $praticien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_praticien_controller_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('praticien_controller_crud/edit.html.twig', [
            'praticien' => $praticien,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_praticien_controller_crud_delete', methods: ['POST'])]
    public function delete(Request $request, Praticien $praticien, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$praticien->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($praticien);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_praticien_controller_crud_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/praticien_controller_crud/_delete_form.html.twig
<form method="post" action="{{ path('app_praticien_controller_crud_delete', {'id': praticien.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ praticien.id) }}">
    <button class="btn">Delete</button>
</form>

templates/praticien_controller_crud/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/praticien_controller_crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Praticien{% endblock %}

{% block body %}
    <h1>Edit Praticien</h1>

    {{ include('praticien_controller_crud/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_praticien_controller_crud_index') }}">back to list</a>

    {{ include('praticien_controller_crud/_delete_form.html.twig') }}
{% endblock %}

templates/praticien_controller_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Praticien index{% endblock %}

{% block body %}
    <h1>Praticien index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Telephone</th>
                <th>Specialite</th>
                <th>Adresse</th>
                <th>NumeroCabinet</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for praticien in praticiens %}
            <tr>
                <td>{{ praticien.id }}</td>
                <td>{{ praticien.nom }}</td>
                <td>{{ praticien.prenom }}</td>
                <td>{{ praticien.telephone }}</td>
                <td>{{ praticien.specialite }}</td>
                <td>{{ praticien.adresse }}</td>
                <td>{{ praticien.numeroCabinet }}</td>
                <td>
                    <a href="{{ path('app_praticien_controller_crud_show', {'id': praticien.id}) }}">show</a>
                    <a href="{{ path('app_praticien_controller_crud_edit', {'id': praticien.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_praticien_controller_crud_new') }}">Create new</a>
{% endblock %}

templates/praticien_controller_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Praticien{% endblock %}

{% block body %}
    <h1>Create new Praticien</h1>

    {{ include('praticien_controller_crud/_form.html.twig') }}

    <a href="{{ path('app_praticien_controller_crud_index') }}">back to list</a>
{% endblock %}

templates/praticien_controller_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Praticien{% endblock %}

{% block body %}
    <h1>Praticien</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ praticien.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ praticien.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ praticien.prenom }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ praticien.telephone }}</td>
            </tr>
            <tr>
                <th>Specialite</th>
                <td>{{ praticien.specialite }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ praticien.adresse }}</td>
            </tr>
            <tr>
                <th>NumeroCabinet</th>
                <td>{{ praticien.numeroCabinet }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_praticien_controller_crud_index') }}">back to list</a>

    <a href="{{ path('app_praticien_controller_crud_edit', {'id': praticien.id}) }}">edit</a>

    {{ include('praticien_controller_crud/_delete_form.html.twig') }}
{% endblock %}